"""count for article

Revision ID: ce6737bddf25
Revises: 4f18e12884a1
Create Date: 2018-05-03 21:57:06.081642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6737bddf25'
down_revision = '4f18e12884a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_article', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_article', 'count')
    # ### end Alembic commands ###
